#!/usr/bin/env python3
"""
Extract and process images from a DOCX file based on an image manifest.

Reads image_manifest.json (generated by build_book.py) and extracts each
image from the DOCX, converting WMF to PNG and applying post-processing
(auto-crop, resize). Writes images to both the JSON pictures directory
and the markdown pictures directory.

Usage:
    python3 process_images.py
"""

import json
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

from build_book import load_book_config

INPUT_DOCX = "original-book.docx"
EXPORT_DIR = "export"
MARKDOWN_DIR = "export_md"


def is_wmf_image(image_data):
    """Check if image data is WMF format by checking magic bytes."""
    if len(image_data) < 4:
        return False
    magic = image_data[:4]
    return magic == b"\xd7\xcd\xc6\x9a" or magic == b"\x01\x00\x09\x00"


def convert_wmf_to_png(wmf_path, output_path):
    """Convert WMF to PNG using LibreOffice -> PDF -> ImageMagick chain."""
    soffice = shutil.which("soffice") or shutil.which("libreoffice")
    if soffice:
        try:
            with tempfile.TemporaryDirectory() as tmpdir:
                result = subprocess.run(
                    [
                        soffice,
                        "--headless",
                        "--convert-to",
                        "pdf",
                        "--outdir",
                        tmpdir,
                        wmf_path,
                    ],
                    capture_output=True,
                    text=True,
                    timeout=30,
                )

                pdf_files = list(Path(tmpdir).glob("*.pdf"))
                if pdf_files:
                    pdf_path = str(pdf_files[0])

                    magick_cmd = None
                    if shutil.which("magick"):
                        magick_cmd = [
                            "magick",
                            "-density",
                            "150",
                            pdf_path,
                            "-flatten",
                            "-trim",
                            "+repage",
                            "png:" + output_path,
                        ]
                    elif shutil.which("convert"):
                        magick_cmd = [
                            "convert",
                            "-density",
                            "150",
                            pdf_path,
                            "-flatten",
                            "-trim",
                            "+repage",
                            "png:" + output_path,
                        ]

                    if magick_cmd:
                        result = subprocess.run(
                            magick_cmd,
                            capture_output=True,
                            text=True,
                            timeout=30,
                        )
                        if result.returncode == 0 and os.path.exists(output_path):
                            with open(output_path, "rb") as f:
                                if f.read(4) == b"\x89PNG":
                                    return True
                            return False

        except subprocess.TimeoutExpired:
            print(f"    Warning: WMF conversion timeout")
            return False
        except Exception as e:
            print(f"    Warning: LibreOffice conversion error: {e}")

    # Fallback: ImageMagick directly
    try:
        magick_cmd = None
        if shutil.which("magick"):
            magick_cmd = ["magick", wmf_path, "png:" + output_path]
        elif shutil.which("convert"):
            magick_cmd = ["convert", wmf_path, "png:" + output_path]
        else:
            print("    Warning: No conversion tools found")
            return False

        result = subprocess.run(magick_cmd, capture_output=True, text=True, timeout=30)
        if result.returncode == 0 and os.path.exists(output_path):
            with open(output_path, "rb") as f:
                if f.read(4) == b"\x89PNG":
                    return True
            return False
        else:
            print(f"    Warning: WMF conversion failed: {result.stderr.strip()}")
            return False
    except subprocess.TimeoutExpired:
        print(f"    Warning: WMF conversion timeout")
        return False
    except Exception as e:
        print(f"    Warning: WMF conversion error: {e}")
        return False


def postprocess_image(image_path, max_size=1200, border=10, white_threshold=240):
    """Auto-crop whitespace and limit resolution of an image."""
    try:
        from PIL import Image, ImageChops
    except ImportError:
        return

    try:
        img = Image.open(image_path)
    except Exception:
        return

    if img.mode not in ("RGB", "L"):
        img = img.convert("RGB")

    bg = Image.new(img.mode, img.size, tuple([white_threshold] * len(img.getbands())))
    diff = ImageChops.subtract(bg, img)
    bbox = diff.getbbox()
    if bbox:
        left, top, right, bottom = bbox
        left = max(0, left - border)
        top = max(0, top - border)
        right = min(img.width, right + border)
        bottom = min(img.height, bottom + border)
        img = img.crop((left, top, right, bottom))

    if max_size > 0:
        longest = max(img.width, img.height)
        if longest > max_size:
            scale = max_size / longest
            new_w = int(img.width * scale)
            new_h = int(img.height * scale)
            img = img.resize((new_w, new_h), Image.LANCZOS)

    img.save(image_path)


def extract_and_save_image(image_data, content_type, output_path):
    """Save image data to output_path, converting format as needed.

    Handles WMF conversion and non-PNG to PNG conversion.
    Returns True on success.
    """
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    if is_wmf_image(image_data):
        wmf_path = output_path + ".wmf.tmp"
        with open(wmf_path, "wb") as f:
            f.write(image_data)

        if convert_wmf_to_png(wmf_path, output_path):
            backup_path = output_path + ".wmf.backup"
            os.rename(wmf_path, backup_path)
        else:
            # Conversion failed, save raw data
            os.remove(wmf_path)
            with open(output_path, "wb") as f:
                f.write(image_data)
    else:
        with open(output_path, "wb") as f:
            f.write(image_data)

        # Convert non-PNG to PNG
        if "png" not in content_type:
            try:
                from PIL import Image

                img = Image.open(output_path)
                img.save(output_path, "PNG")
            except (ImportError, Exception):
                pass

    postprocess_image(output_path)
    return True


def validate_images(json_dir, images_dir):
    """Validate image references in JSON against files on disk."""
    import glob as glob_mod

    json_refs = set()
    for jf in glob_mod.glob(f"{json_dir}/**/*.json", recursive=True):
        try:
            with open(jf, "r", encoding="utf-8") as f:
                data = json.load(f)
            for item in data.get("content", []):
                if item.get("type") == "image" and item.get("path"):
                    json_refs.add(item["path"])
        except (json.JSONDecodeError, KeyError):
            continue

    disk_files = set()
    for root, dirs, files in os.walk(images_dir):
        for f in files:
            if f.endswith((".png", ".jpg")) and ".backup" not in f:
                rel = os.path.relpath(os.path.join(root, f), images_dir)
                disk_files.add(f"pictures/{rel}")

    missing_on_disk = json_refs - disk_files
    orphaned_on_disk = disk_files - json_refs

    print("\n" + "=" * 80)
    print("POST-GENERATION IMAGE VALIDATION")
    print("=" * 80)

    if missing_on_disk:
        print(f"\nERROR: {len(missing_on_disk)} JSON refs with no file on disk:")
        for p in sorted(missing_on_disk):
            print(f"  {p}")
    else:
        print("\nAll JSON image references have matching files on disk.")

    if orphaned_on_disk:
        print(f"\nWARNING: {len(orphaned_on_disk)} image files not referenced in JSON:")
        for p in sorted(orphaned_on_disk):
            print(f"  {p}")
    else:
        print("No orphaned image files found.")

    if not missing_on_disk and not orphaned_on_disk:
        print("\nAll image checks passed.")
    print("=" * 80)

    return {
        "all_passed": not missing_on_disk and not orphaned_on_disk,
        "missing_on_disk": sorted(missing_on_disk),
        "orphaned_on_disk": sorted(orphaned_on_disk),
    }


def process_images():
    """Main entry point: extract and process all images from the DOCX."""
    print("=" * 80)
    print("PROCESS IMAGES")
    print("=" * 80)

    # Load config (reuse build_book's config loader for canonical_id derivation)
    config = load_book_config(INPUT_DOCX)
    lang = config.get("language", "eng")
    book_id = config["canonical_id"]
    pictures_location = config.get("pictures_location", "root")

    json_book_dir = os.path.join(EXPORT_DIR, lang, book_id)
    manifest_path = os.path.join(json_book_dir, "image_manifest.json")

    if not os.path.exists(manifest_path):
        print(f"Error: {manifest_path} not found. Run 'make build' first.")
        sys.exit(1)

    with open(manifest_path, "r", encoding="utf-8") as f:
        manifest = json.load(f)

    images = manifest.get("images", [])
    if not images:
        print("No images to process.")
        return

    print(f"Found {len(images)} images in manifest")

    # Open DOCX to extract image blobs
    if not os.path.exists(INPUT_DOCX):
        print(f"Error: {INPUT_DOCX} not found.")
        sys.exit(1)

    from docx import Document

    print(f"Opening {INPUT_DOCX}...")
    doc = Document(INPUT_DOCX)

    # Build rId -> image_part lookup
    related_parts = doc.part.related_parts

    processed = 0
    skipped = 0
    failed = 0

    for entry in images:
        img_idx = entry["image_index"]
        r_id = entry["rId"]
        content_type = entry.get("content_type", "")
        section_path = entry["section_path"]
        filename = entry["filename"]
        chapter_dir = entry.get("chapter_dir", "")

        # Determine output path for JSON pictures
        if pictures_location == "root":
            pictures_dir = os.path.join(
                EXPORT_DIR, "pictures", lang, book_id, section_path
            )
        elif pictures_location == "book":
            pictures_dir = os.path.join(
                EXPORT_DIR, lang, book_id, "pictures", section_path
            )
        else:
            chapter_part = (
                section_path.split("/")[0] if "/" in section_path else section_path
            )
            pictures_dir = os.path.join(
                EXPORT_DIR, lang, book_id, chapter_part, "pictures"
            )

        output_path = os.path.join(pictures_dir, filename)

        # Skip if already exists
        if os.path.exists(output_path):
            skipped += 1
            continue

        # Extract image blob from DOCX
        if r_id not in related_parts:
            print(f"  Warning: rId '{r_id}' not found for image {img_idx}")
            failed += 1
            continue

        image_part = related_parts[r_id]
        image_data = image_part.blob

        # Save and process
        extract_and_save_image(image_data, content_type, output_path)
        processed += 1

        if processed % 50 == 0:
            print(f"  Processed {processed} images...")

        # Also save to markdown directory
        if os.path.exists(MARKDOWN_DIR) and chapter_dir:
            md_pictures_dir = os.path.join(MARKDOWN_DIR, chapter_dir, "pictures")
            md_output_path = os.path.join(md_pictures_dir, filename)
            if not os.path.exists(md_output_path):
                # Copy from already-processed JSON image
                os.makedirs(md_pictures_dir, exist_ok=True)
                shutil.copy2(output_path, md_output_path)

    print(f"\nProcessed: {processed}, Skipped (existing): {skipped}, Failed: {failed}")

    # Create pictures manifest.json
    manifest_data = {}
    for entry in images:
        section_path = entry["section_path"]
        filename = entry["filename"]
        manifest_data[f"{section_path}/{filename}"] = {
            "alt": entry.get("alt", ""),
            "caption": entry.get("caption", ""),
        }

    if manifest_data:
        if pictures_location == "root":
            pictures_root = os.path.join(EXPORT_DIR, "pictures", lang, book_id)
        else:
            pictures_root = os.path.join(json_book_dir, "pictures")
        os.makedirs(pictures_root, exist_ok=True)
        pics_manifest_path = os.path.join(pictures_root, "manifest.json")
        with open(pics_manifest_path, "w", encoding="utf-8") as f:
            json.dump(manifest_data, f, indent=2)
        print(f"Created {pics_manifest_path}")

    # Validate
    if pictures_location == "root":
        images_root = os.path.join(EXPORT_DIR, "pictures", lang, book_id)
    else:
        images_root = os.path.join(json_book_dir, "pictures")

    if os.path.exists(images_root):
        validation = validate_images(json_book_dir, images_root)

        # Update postprocess.json with validation results
        postprocess_path = os.path.join(json_book_dir, "postprocess.json")
        if os.path.exists(postprocess_path):
            with open(postprocess_path, "r", encoding="utf-8") as f:
                postprocess = json.load(f)
            postprocess["image_validation"] = validation
            with open(postprocess_path, "w", encoding="utf-8") as f:
                json.dump(postprocess, f, indent=2)
            print(f"Updated {postprocess_path} with validation results")

    print("\n" + "=" * 80)
    print("Image processing complete!")
    print("=" * 80)


if __name__ == "__main__":
    try:
        process_images()
    except Exception as e:
        print(f"\nError: {e}")
        import traceback

        traceback.print_exc()
        sys.exit(1)
